language: php-cli

php:
  - 5.6

addons:
  hosts:
    - mysql

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $PREFER_LOWEST
  - composer install

script:
  - vendor/bin/phpcs -p ./src --standard=PHPCompatibility,PSR2 --runtime-set testVersion 5.6-
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_success:
  bash <(curl -s https://codecov.io/bash)
