version: '2'

services:
  php-cli:
    build:
      context: .docker/build/php-cli
      args:
        LOCAL_USER_ID: $DOCKER_LOCAL_USER_ID
        LOCAL_GROUP_ID: $DOCKER_LOCAL_USER_GROUP
    user: $DOCKER_LOCAL_USER_ID:$DOCKER_LOCAL_USER_GROUP
    volumes:
      - ./:/var/www
    tty: true
    stdin_open: true
    networks:
      - janisbiz_heredoc

networks:
  janisbiz_heredoc:
    driver: bridge
